-- MySQL Script generated by MySQL Workbench
-- Thu Jan 18 00:05:44 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema ShoeStore
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema ShoeStore
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ShoeStore` DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ;
USE `ShoeStore` ;

-- -----------------------------------------------------
-- Table `ShoeStore`.`Gender`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ShoeStore`.`Gender` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `gender` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

INSERT INTO `ShoeStore`.`Gender` (`gender`) VALUES ('Žensko');
INSERT INTO `ShoeStore`.`Gender` (`gender`) VALUES ('Muško');
-- -----------------------------------------------------
-- Table `ShoeStore`.`ArticleType`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ShoeStore`.`ArticleType` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `type` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

INSERT INTO `ShoeStore`.`ArticleType` (`type`) VALUES ('Patike');
INSERT INTO `ShoeStore`.`ArticleType` (`type`) VALUES ('Čizme');
INSERT INTO `ShoeStore`.`ArticleType` (`type`) VALUES ('Papuče');
INSERT INTO `ShoeStore`.`ArticleType` (`type`) VALUES ('Sandale');
INSERT INTO `ShoeStore`.`ArticleType` (`type`) VALUES ('Štikle');
INSERT INTO `ShoeStore`.`ArticleType` (`type`) VALUES ('Gležnjerice');
INSERT INTO `ShoeStore`.`ArticleType` (`type`) VALUES ('Cipele');

-- -----------------------------------------------------
-- Table `ShoeStore`.`Article`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ShoeStore`.`Article` (
  `idArticle` INT NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `picture` VARCHAR(255) NOT NULL,
  `supplyPrice` DECIMAL(5,2) NOT NULL,
  `sellPrice` DECIMAL(5,2) NOT NULL,
  `Gender_id` INT NOT NULL,
  `ArticleType_id` INT NOT NULL,
  `active` TINYINT NOT NULL,
  PRIMARY KEY (`idArticle`),
  INDEX `fk_Artical_Gender1_idx` (`Gender_id` ASC) VISIBLE,
  INDEX `fk_Artical_ArticleType1_idx` (`ArticleType_id` ASC) VISIBLE,
  CONSTRAINT `fk_Artical_Gender1`
    FOREIGN KEY (`Gender_id`)
    REFERENCES `ShoeStore`.`Gender` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Artical_ArticleType1`
    FOREIGN KEY (`ArticleType_id`)
    REFERENCES `ShoeStore`.`ArticleType` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ShoeStore`.`ArticleItem`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ShoeStore`.`ArticleItem` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `size` INT NOT NULL,
  `quantity` INT NOT NULL,
  `Article_idArticle` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_ArticleItem_Article1_idx` (`Article_idArticle` ASC) VISIBLE,
  CONSTRAINT `fk_ArticleItem_Article1`
    FOREIGN KEY (`Article_idArticle`)
    REFERENCES `ShoeStore`.`Article` (`idArticle`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `ShoeStore`.`Employee`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ShoeStore`.`Employee` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `lastname` VARCHAR(45) NOT NULL,
  `username` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `phoneNumber` VARCHAR(45) NOT NULL,
  `role` VARCHAR(45) NOT NULL,
  `active` TINYINT NOT NULL,
  `language` VARCHAR(45) NULL,
  `theme` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

INSERT INTO `shoestore`.`employee` (`name`, `lastname`, `username`, `password`, `email`, `phoneNumber`, `role`, `active`, `language`, `theme`) VALUES ('Marko', 'Markovic', 'marko', 'marko', 'marko@gmail.com', '066123456', 'admin', '1', '1', '1');
INSERT INTO `shoestore`.`employee` (`name`, `lastname`, `username`, `password`, `email`, `phoneNumber`, `role`, `active`, `language`, `theme`) VALUES ('Milica', 'Milic', 'milica', 'milica', 'milica@gmail.com', '066123456', 'admin', '1', '1', '1');
INSERT INTO `shoestore`.`employee` (`name`, `lastname`, `username`, `password`, `email`, `phoneNumber`, `role`, `active`, `language`, `theme`) VALUES ('Jovana', 'Jovanovic', 'jovana', 'jovana', 'jovana@gmail.com', '066123456', 'emp', '1', '1', '1');
INSERT INTO `shoestore`.`employee` (`name`, `lastname`, `username`, `password`, `email`, `phoneNumber`, `role`, `active`, `language`, `theme`) VALUES ('Nikola', 'Nikolic', 'nikola', 'nikola', 'nikola@gmail.com', '066123456', 'emp', '1', '1', '1');


-- -----------------------------------------------------
-- Table `ShoeStore`.`Supplier`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ShoeStore`.`Supplier` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `phoneNumber` VARCHAR(255) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

INSERT INTO `ShoeStore`.`Supplier` (`name`, `phoneNumber`, `email`) VALUES ('Juventa', '065478124', 'juventa@gmail.com');
INSERT INTO `ShoeStore`.`Supplier` (`name`, `phoneNumber`, `email`) VALUES ('Borovo', '065741396', 'borovo@gmail.com');
INSERT INTO `ShoeStore`.`Supplier` (`name`, `phoneNumber`, `email`) VALUES ('SportVision', '065852314', 'sportvision@gmail.com');
INSERT INTO `ShoeStore`.`Supplier` (`name`, `phoneNumber`, `email`) VALUES ('Planika', '065123789', 'planika@gmail.com');


-- -----------------------------------------------------
-- Table `ShoeStore`.`Supply`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ShoeStore`.`Supply` (
  `idSupply` INT NOT NULL AUTO_INCREMENT,
  `date` DATETIME NOT NULL,
  `totalPrice` DECIMAL NOT NULL,
  `Employee_id` INT NOT NULL,
  `Supplier_id` INT NOT NULL,
  PRIMARY KEY (`idSupply`),
  INDEX `fk_Nabavka_Employee1_idx` (`Employee_id` ASC) VISIBLE,
  INDEX `fk_Nabavka_Supplier1_idx` (`Supplier_id` ASC) VISIBLE,
  CONSTRAINT `fk_Nabavka_Employee1`
    FOREIGN KEY (`Employee_id`)
    REFERENCES `ShoeStore`.`Employee` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Nabavka_Supplier1`
    FOREIGN KEY (`Supplier_id`)
    REFERENCES `ShoeStore`.`Supplier` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ShoeStore`.`SupplyItem`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ShoeStore`.`SupplyItem` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `quantity` INT NOT NULL,
  `price` DECIMAL(5,2) NOT NULL,
  `ArticleItem_id` INT NOT NULL,
  `Supply_idSupply` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_SupplyItem_ArticleItem1_idx` (`ArticleItem_id` ASC) VISIBLE,
  INDEX `fk_SupplyItem_Supply1_idx` (`Supply_idSupply` ASC) VISIBLE,
  CONSTRAINT `fk_SupplyItem_ArticleItem1`
    FOREIGN KEY (`ArticleItem_id`)
    REFERENCES `ShoeStore`.`ArticleItem` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_SupplyItem_Supply1`
    FOREIGN KEY (`Supply_idSupply`)
    REFERENCES `ShoeStore`.`Supply` (`idSupply`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ShoeStore`.`Bill`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ShoeStore`.`Bill` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `date` DATETIME NOT NULL,
  `totalPrice` DECIMAL(10,2) NOT NULL,
  `Employee_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Bill_Employee1_idx` (`Employee_id` ASC) VISIBLE,
  CONSTRAINT `fk_Bill_Employee1`
    FOREIGN KEY (`Employee_id`)
    REFERENCES `ShoeStore`.`Employee` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ShoeStore`.`BillItem`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ShoeStore`.`BillItem` (
  `quantity` INT NOT NULL,
  `price` DECIMAL(5,2) NOT NULL,
  `Bill_id` INT NOT NULL,
  `ArticleItem_id` INT NOT NULL,
  PRIMARY KEY (`Bill_id`, `ArticleItem_id`),
  INDEX `fk_BillItem_Bill1_idx` (`Bill_id` ASC) VISIBLE,
  INDEX `fk_BillItem_ArticleItem1_idx` (`ArticleItem_id` ASC) VISIBLE,
  CONSTRAINT `fk_BillItem_Bill1`
    FOREIGN KEY (`Bill_id`)
    REFERENCES `ShoeStore`.`Bill` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_BillItem_ArticleItem1`
    FOREIGN KEY (`ArticleItem_id`)
    REFERENCES `ShoeStore`.`ArticleItem` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
